# NAME THE PIPELINE SAME AS FILE (WITHOUT ".yml")
# Good practice: pipeline name = YAML file name

# trigger:
# - main
# Automatic trigger on push to main (disabled here for demo purposes)

resources:
  repositories:
    - repository: self
      # Use current repository
      trigger: none
      # Disable automatic triggers

stages:
# Define stages of the pipeline
- stage: Build
  displayName: Build .Net Core Solution

  jobs:
  # A job runs on an agent
  - job: Build

    pool:
      vmImage: ubuntu-latest
      # Microsoft-hosted agent (Linux)

    steps:
    # Steps are executed sequentially

    # Restore NuGet dependencies
    - task: DotNetCoreCLI@2
      displayName: Restore
      inputs:
        command: 'restore'
        projects: '**/*.sln'
        feedsToUse: 'select'

    # Build the application
    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: 'build'
        projects: '**/*.sln'  # Path to the projects to build
                              # **/*.sln means: all solution files in the repository
                              # This ensures the entire application is built

    # Run unit tests
    - task: DotNetCoreCLI@2
      displayName: Test
      inputs:
        command: 'test'
        projects: 'tests/UnitTests/*.csproj'   # Path to the test projects
                                                # tests/UnitTests/*.csproj means: all test project files in this folder
                                                # Only unit tests will be executed here

    # Publish application (prepare for deployment)
    - task: DotNetCoreCLI@2
      displayName: Publish
      inputs:
        command: 'publish'       # → Prepares the application for deployment (compiles + packages output)
        publishWebProjects: true # Automatically targets all web projects in the solution
                                 # Ensures only deployable web apps are published
        arguments: '-o $(Build.ArtifactStagingDirectory)'  # Output directory for the published files
                                                           # $(Build.ArtifactStagingDirectory) is a temporary folder used to store artifacts

    # Publish application artifact
    - task: PublishPipelineArtifact@1
      displayName: Publish Artifacts - Website
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)'  # Path of the files to publish , $(Build.ArtifactStagingDirectory) contains the output from the publish step
        artifact: 'Website'                              # This is how the artifact will be referenced in later stages
        publishLocation: 'pipeline'                      # Location where the artifact will be stored , 'pipeline' means it will be stored within Azure DevOps pipeline storage
